find_program(XXD_PROGRAM xxd)
if( NOT XXD_PROGRAM STREQUAL "XXD_PROOGRAM-NOTFOUND")
	EXECUTE_PROCESS(
		COMMAND ${XXD_PROGRAM} -i
		INPUT_FILE "${SAMPLE}"
		OUTPUT_VARIABLE SAMPLE_FILE_CONTENTS
		OUTPUT_STRIP_TRAILING_WHITESPACE
		RESULT_VARIABLE SAMPLE_SUCCESS
	)
endif()
if(NOT SAMPLE_SUCCESS EQUAL 0)
	SET(SAMPLE_FILE_CONTENTS "'S', 'a', 'm', 'p', 'l', 'e', ' ', 'n', 'o', 't', ' ', 'f', 'o', 'u', 'n', 'd', '.'")
endif()
CONFIGURE_FILE(${SRC} ${DST} @ONLY)
